name: Beautiq
description: A salons booking app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^4.4.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.1.2
  add_2_calendar: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/salons/salon_1.png
    - assets/images/salons/salon_2.png
    - assets/images/salons/salon_3.png
    - assets/images/salons/salon_4.png
    - assets/images/services/haircut.png
    - assets/images/services/shaving.png
    - assets/images/services/massage.png
    - assets/images/services/facial.png
    - assets/images/services/threading.png
    - assets/images/services/makeup.png
    - assets/images/onboarding/slide1.png
    - assets/images/onboarding/slide2.png
    - assets/images/onboarding/slide3.png


